---
- name: Dev Env Setup Playbook
  hosts: devbox

  vars_files:
    # Apps and Extensions
    - variables/homebrew-apps.yml
    - variables/npm-packages.yml
    - variables/vsc-extensions.yml

  vars:
    maven_path: "{{ ansible_env.HOME }}/dev/tools/maven"

  tasks:

    - name: Seting up properties
      import_tasks: tasks/repositories/setup_properties.yml
    
    # Git
    - name: Generate SSH Key
      import_tasks: tasks/repositories/create_ssh_key.yml

    - name: Setup Git
      import_tasks: tasks/repositories/setup_git.yml

    # Install core applications
    - name: Install applications
      import_tasks: tasks/installation/install_applications.yml

    # TODO: Add VNC: 
    # https://medium.com/@thedyslexiccoder/setting-up-a-vnc-screen-share-on-a-raspberry-pi-and-a-mac-10c1635df5dc#:~:text=Open%20the%20Screen%20Sharing%20App,Click%20Sign%20In!
    # TODO: Add NVM to Path: 
    # https://tecadmin.net/install-nvm-macos-with-homebrew/
    - name: Install NVM, Node and NPM Packages
      import_tasks: tasks/installation/install_node_nvm_packages.yml

    # Setup development tools
    - name: Download AWS Coretto Java 8, 11 & 17
      import_tasks: tasks/dev_tools/download_java.yml

    - name: Setup Maven
      import_tasks: tasks/dev_tools/setup_maven.yml

    # Customization & misc
    - name: Install VSCode extensions
      import_tasks: tasks/customization/customize_vscode.yml

    - name: Setup ZSH Aliases
      import_tasks: tasks/customization/setup_zsh_aliases.yml