---
- name: Dev Env Setup Playbook
  hosts: devbox

  # https://www.google.com/search?q=dot+files+java+macos+ansible+playbook
  # FOCUS: https://www.google.com/search?q=dot+files+java+macos+ansible+playbook

  # https://www.atpeaz.com/macos-set-up-for-coding-and-development/
  # https://medium.com/@gareth.stretton/obsidian-control-from-chrome-1ba27c5ef84b
  
  # Purpose: Search vault
  # Search Engine: Obsidian - Search
  # Shortcut: obs
  # URL: obsidian://search?vault=my_vault&query=%s

  # Purpose: Create a new note
  # Search Engine: Obsidian - Create Note
  # Shortcut: obn
  # URL: obsidian://new?vault=my_vault&silent=true&name=%s

  # Purpose: Save a link to a note
  # Search Engine: Obsidian - Save Link
  # Shortcut: obl
  # URL: obsidian://new?vault=my_vault&silent=true&name=Links&append=true&content=%s%0D%0A

  # Purpose: Save a TODO to a note
  # Search Engine: Obsidian - Save TODO
  # Shortcut: obn
  # URL: obsidian://new?vault=my_vault&silent=true&name=TODOs&append=true&content=-%20[%20]%20%s%0D%0A

  vars_files:
    # Apps and Extensions
    - variables/homebrew-apps.yml
    - variables/npm-packages.yml
    - variables/vsc-extensions.yml

  vars:
    maven_path: "{{ ansible_env.HOME }}/dev/tools/maven"
    zshrc_path: "{{ ansible_env.HOME }}/.zshrc"
    shell_rc: "{{ ansible_env.HOME }}/.zshrc_playground"
    shell_aliases: "{{ ansible_env.HOME }}/.zsh_aliases_playground"
    git_config: "{{ ansible_env.HOME }}/.gitconfig"

  vars_prompt:
    - name: "dry_run"
      prompt: "Dry run only?"
      default: yes
      private: no

    - name: "env"
      prompt: "Which environment should be targeted?"
      default: dev
      private: no

  tasks:
    - name: Dry run summary
      debug:
        msg: "Dry run ... {{env}} Exiting"
      when: dry_run | bool

    # https://github.com/asjafjell/ansible/blob/master/work/roles/jenv/tasks/main.yml
    # https://www.google.com/search?q=java+%22jenv%22+ansible+script
    - name: Check if string is present
      shell: grep -q "jenv" {{zshrc_path}}
      register: grep_zshrc_result
      changed_when: false

    - name: Execute something if string is found
      debug:
        msg: "zshrc_path: {{zshrc_path}}"
      when: grep_zshrc_result.rc == 0

    - name: common_tasks
      import_tasks: ../common/tasks/setup_properties.yml
      when: not (dry_run | bool)

    - name: Seting up properties
      import_tasks: tasks/repositories/setup_properties.yml
      when: not (dry_run | bool)
    
    # Git
    - name: Generate SSH Key
      import_tasks: tasks/repositories/create_ssh_key.yml
      when: not (dry_run | bool)

    - name: Setup Git
      import_tasks: tasks/repositories/setup_git.yml
      when: not (dry_run | bool)

    # https://github.com/mark-omarov/dotfiles/blob/main/git/.gitconfig
    # TODO
    - name: Setup Git Aliases
      import_tasks: ../common/tasks/setup_git_aliases.yml
      when: not (dry_run | bool)

    # Install core applications
    - name: Install applications
      import_tasks: tasks/installation/install_applications.yml
      when: not (dry_run | bool)

    # TODO: Add VNC: 
    # https://medium.com/@thedyslexiccoder/setting-up-a-vnc-screen-share-on-a-raspberry-pi-and-a-mac-10c1635df5dc#:~:text=Open%20the%20Screen%20Sharing%20App,Click%20Sign%20In!
    # TODO: Add NVM to Path: 
    # https://tecadmin.net/install-nvm-macos-with-homebrew/
    - name: Install NVM, Node and NPM Packages
      import_tasks: tasks/installation/install_node_nvm_packages.yml
      when: not (dry_run | bool)

    # Setup development tools
    - name: Download AWS Coretto Java 8, 11 & 17
      import_tasks: tasks/dev_tools/download_java.yml
      when: not (dry_run | bool)

    # FIXME - Need to be reviewed
    # - name: Setup Maven
    #   import_tasks: tasks/dev_tools/setup_maven.yml
    #   when: not (dry_run | bool)

    # Customization & misc
    - name: Install VSCode extensions
      import_tasks: tasks/customization/customize_vscode.yml
      when: not (dry_run | bool)

    - name: Setup OhMyZsh
      import_tasks: tasks/installation/install_ohmyzsh.yml
      when: not (dry_run | bool)

    - name: Setup ZSH
      include_tasks: ../common/customization/setup_sh.yml
      when: not (dry_run | bool)

    - name: Setup ZSH Aliases
      include_tasks: ../common/customization/setup_sh_aliases.yml
      when: not (dry_run | bool)

    - name: Setup Git Aliases
      include_tasks: ../common/customization/setup_git_aliases.yml
      when: not (dry_run | bool)

    # https://medium.com/@gareth.stretton/obsidian-control-from-chrome-1ba27c5ef84b
    - name: Set URLAllowlist for Obsidian
      shell: defaults write com.google.Chrome URLAllowlist -array 'obsidian://*'
      become: yes
      become_method: sudo
      become_user: root
