- name: Check if Java is already installed
  stat:
    path: /usr/bin/java
  register: javaBinary
  tags:
    - brew

- name: Download Java 8
  get_url:
    url: "https://corretto.aws/downloads/latest/amazon-corretto-8-x64-macos-jdk.pkg"
    dest: "{{ansible_env.HOME}}/Downloads"
    mode: '0555'
    force: no
  when: not javaBinary.stat.exists

- name: Download Java 11
  get_url:
    url: "https://corretto.aws/downloads/latest/amazon-corretto-11-x64-macos-jdk.pkg"
    dest: "{{ansible_env.HOME}}/Downloads"
    mode: '0555'
    force: no
  when: not javaBinary.stat.exists

- name: Download Java 17
  get_url:
    url: "https://corretto.aws/downloads/latest/amazon-corretto-17-x64-macos-jdk.pkg"
    dest: "{{ansible_env.HOME}}/Downloads"
    mode: '0555'
    force: no
  when: not javaBinary.stat.exists

- pause:
    prompt: "Java 8, 11 and 17 were downloaded in your Downloads folder. Please install them by running the executables (press ENTER to continue)"
  register: name
  delegate_to: localhost
  when: not javaBinary.stat.exists