- name: Remove None values from brew_cask_apps
  set_fact:
    brew_cask_apps_filtered: "{{ brew_cask_apps | select('string') | list }}"

- name: Debug filtered brew_cask_apps
  debug:
    msg: "Filtered brew_cask_apps: {{ brew_cask_apps_filtered }}"

- name: Install brew cask apps
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items: "{{brew_cask_apps_filtered}}"
  ignore_errors: True
  tags:
    - brew

- name: Remove None values from brew_apps
  set_fact:
    brew_apps_filtered: "{{ brew_apps | select('string') | list }}"

- name: Debug filtered brew_apps
  debug:
    msg: "Filtered brew_apps: {{ brew_apps_filtered }}"

- name: Install brew apps
  homebrew:
    name: "{{ brew_apps_filtered }}"
    state: present
    update_homebrew: yes
  ignore_errors: true
  when: brew_apps_filtered | length > 0
  tags:
    - brew