# This step is necessary to make sure NVM runs properly. See https://github.com/nvm-sh/nvm#troubleshooting-on-macos
- name: "Create .zshrc file"
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch
    mode: u=rw,g=r,o=r # User, Group, Others. Setting 644 permissions

# https://ohmyz.sh/#install
- name: "install oh-my-zsh"
  shell: >
    curl -o- https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"