- name: Add Aliases
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      # Load aliases
      if [ -f ~/.zsh_aliases ]; then
        . ~/.zsh_aliases
      fi

      # Maven aliases
      alias mvc="mvn clean generate-sources"
      alias mvct="mvc && mvn test"

      # Java version switch
      alias j17="export JAVA_HOME=`/usr/libexec/java_home -v 17`; java -version"
      alias j11="export JAVA_HOME=`/usr/libexec/java_home -v 11`; java -version"
      alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"

      removecontainers() {
        docker stop $(docker ps -aq)
        docker rm $(docker ps -aq)
      }

      armageddon() {
          removecontainers
          docker network prune -f
          docker rmi -f $(docker images --filter dangling=true -qa)
          docker volume rm $(docker volume ls --filter dangling=true -q)
          docker rmi -f $(docker images -qa)
      }