# TODO Make these tasks fully idempotent under a conditional block.

- name: SSH Setup - Set up file and folder names
  set_fact:
    ssh_file_name: id_rsa
    ssh_key_base_folder: "{{ ansible_env.HOME }}/.ssh"

- name: Create .ssh directory
  file:
    path: "{{ssh_key_base_folder}}" # ~/.ssh
    state: directory

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "{{ssh_key_base_folder}}/{{ssh_file_name}}" # ~/.ssh
    mode: 0400 # Read-only by current user. Note: The leading 0 tells Ansible the number is an Octal 
    comment: SSH key

- debug:
    msg: Created an SSH key on "{{ssh_key_base_folder}}"

- name: Enable SSH Agent and ssh-add key
  shell: eval `ssh-agent`

- name: ssh-add key
  shell: ssh-add /{{ssh_key_base_folder}}/{{ssh_file_name}}


- name: Create SSH config file
  register: ssh_config_directory
  copy:
    dest: "{{ssh_key_base_folder}}/config" # ~/.ssh/config
    content: |
      Host *
      UseKeychain yes
    mode: 0600

- name: Get public key's contents
  command: cat /{{ssh_key_base_folder}}/{{ssh_file_name}}.pub
  register: public_key_contents

- name: Print public key's contents
  debug:
    msg: "{{public_key_contents.stdout | default('Key contents not found')}}"


- pause:
    prompt: Copy the content of the "msg" (not including quotes) above to your GitHub/BitBucket account's keys. Press ENTER when done