# Source: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
# https://docs.ansible.com/ansible/2.6/modules/git_config_module.html
- name: Setup git e-mail
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ user_email }}"
  when: user_email_config.config_value == ""

- name: Setup git name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ user_name }}"
  when: user_name_config.config_value == ""