# Git - Email
- name: Read email from git config
  community.general.git_config:
    name: user.email
    scope: global
  register: user_email_config

- debug:
    msg: "Git user.email already defined: {{ user_email_config.config_value }}"
  when: user_email_config.config_value != ""

- name: Setup Git Email
  pause:
    prompt: "What is your email?"
  register: user_email_input
  delegate_to: localhost
  when: user_email_config.config_value == ""

- name: "Set User Email when already configured"
  set_fact:
    user_email: "{{ user_email_config.config_value }}"
  when: user_email_config.config_value != ""

- name: "Set User Email when not configured"
  set_fact:
    user_email: "{{ user_email_input.user_input }}"
  when: user_email_config.config_value == ""

- debug:
    msg: "User Email: {{ user_email }}"

# Git - Name
- name: Read email from git config
  community.general.git_config:
    name: user.email
    scope: global
  register: user_email_config

- debug:
    msg: "Git user.email already defined: {{ user_email_config.config_value }}"
  when: user_email_config.config_value != ""

- name: Setup Git Email
  pause:
    prompt: "What is your email?"
  register: user_email_input
  delegate_to: localhost
  when: user_email_config.config_value == ""

- name: "Set User Email when already configured"
  set_fact:
    user_email: "{{ user_email_config.config_value }}"
  when: user_email_config.config_value != ""

- name: "Set User Email when not configured"
  set_fact:
    user_email: "{{ user_email_input.user_input }}"
  when: user_email_config.config_value == ""

- debug:
    msg: "User Email: {{ user_email }}"